stolostron/cluster-proxy

- cmd/pure.Dockerfile
> Add a dockerfile to support build prue cluster-proxy without ANP

- OWNERS
> Modify the owners to suit the CICD flow

- Makefile.prow
> Add makefile.prow

- Makefile
> Add make pure.Dockerfile

- go.sum
- vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
- vendor/modules.txt
- vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addonfactory.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/helm_agentaddon.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/template_agentaddon.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/trimcrds.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/constants/constants.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/addonhealthcheck/controller.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/addoninstall/controller.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/hookcontroller.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/utils.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/certificate/csrapprove.go
- vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/manager.go
- vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go
- vendor/open-cluster-management.io/addon-framework/pkg/utils/csr_helpers.go
- vendor/open-cluster-management.io/addon-framework/pkg/utils/permission.go
- vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go
> Update the vendor

- pkg/common/constants.go
> Change agent addon default install namespace

- cmd/pure.Dockerfile
https://github.com/stolostron/backlog/issues/22707
> update dockerfile image to go 1.18

- sonar-project.properties
https://github.com/stolostron/backlog/issues/23658
> Add sonar scan

- sonar-project.properties
> Improve coverage score of cluster-proxy

- sonar-project.properties
> Update sonar configuration to exclude test files

- sonar-project.properties
> Update go version 1.18

- vendor/k8s.io/client-go/transport/round_trippers.go
> Upgrade go 1.19 on midstream.

- sonar-project.properties
> Fix: sonar configuration of cluster-proxy to improve coverage.

- vendor/k8s.io/client-go/transport/round_trippers.go
> Fix an typo in vendor file.

- sonar-project.properties
> Add client code to sonar exclusion.

- pkg/proxyagent/agent/agent.go
https://github.com/stolostron/backlog/issues/25872
> Change installstragety to avoid install cluster-proxy in hosted mode.

- pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml
Fixes: https://coreos.slack.com/archives/CTDEY6EEA/p1670324464574639
In the future, we need to make resource quota configurable(maybe via addon template)
> Remove addon pods resource quota.

- cmd/pure.Dockerfile
> Upgrade dockerfile using go version 1.19

- .tekton/cluster-proxy-plyk-pull-request.yaml
- .tekton/cluster-proxy-plyk-push.yaml
- cmd/Dockerfile.rhtap
Fix: https://issues.redhat.com/browse/ACM-7262
> Add dockerfile for rhtap

- pkg/proxyagent/stolostronagent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml
related PR: https://github.com/open-cluster-management-io/cluster-proxy/pull/171
related Issue: https://issues.redhat.com/browse/ACM-8831
> Merge upstream scc changes.

- pkg/proxyagent/stolostronagent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml
- pkg/proxyagent/stolostronagent/manifests/charts/addon-agent/templates/service-account.yaml
issue: https://issues.redhat.com/browse/ACM-9759
> move imagepullsecret to sa from deployment

- cmd/addon-manager/main.go
Fixes: https://issues.redhat.com/browse/ACM-12411
Related Upstream PR: https://github.com/open-cluster-management-io/cluster-proxy/pull/196
> Add leaderelection in addon-manager in mce 2.5

- cmd/addon-manager/main.go
Fixes: https://issues.redhat.com/browse/ACM-12411 
Related Upstream PR: https://github.com/open-cluster-management-io/cluster-proxy/pull/196
> Add leaderelection on mce 2.4

- .tekton/cluster-proxy-mce-26-pull-request.yaml
- .tekton/cluster-proxy-mce-26-push.yaml
Migration based on: https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
> konflux migration.

- .tekton/cluster-proxy-mce-28-pull-request.yaml
- .tekton/cluster-proxy-mce-28-push.yaml
This PR:
- Formatting all tekton files
- Update konflux CEL from backplane-2.8 to main
> :seedling: [main] update konflux files

- .tekton/cluster-proxy-mce-28-pull-request.yaml
- .tekton/cluster-proxy-mce-28-push.yaml
- cmd/Dockerfile.rhtap
- Enable hermetic builds for pull request and push Tekton pipelines
- Add prefetch-input for Go module dependencies
- Update Dockerfile to use readonly module flag
- Add comprehensive container image labels to Dockerfile
- Remove vendor step and unnecessary label duplications
> Enable Hermetic Builds

- .tekton/cluster-proxy-mce-28-pull-request.yaml
- .tekton/cluster-proxy-mce-28-push.yaml
This PR:
- Update konflux CEL from main to backplane-2.8
> :seedling: [backplane-2.8] update konflux files

- pkg/proxyagent/agent/agent.go
- pkg/proxyagent/agent/agent_test.go
- pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-clusterrole.yaml
- pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-clusterrolebinding.yaml
- pkg/proxyagent/agent/manifests/charts/addon-agent/templates/addon-agent-deployment.yaml
- pkg/proxyagent/agent/manifests/charts/addon-agent/values.yaml
Related Story: https://issues.redhat.com/browse/ACM-19584
> Add permissions needed for impersonation.
